In [4]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as num

In [5]:


# Load dataset
df = pd.read_csv('tip.csv')

# Remove columns
df = df.drop(['sex', 'smoker', 'day', 'time', 'size'], axis=1)

# Remove rows
df = df.drop(df.index[10:241])

# Reset index (important)
df = df.reset_index(drop=True)

# Save cleaned dataset as CSV
df.to_csv("cleaned_tip.csv", index=False)

print("CSV file created successfully!")

CSV file created successfully!

In [6]:
sns.histplot(data=df, x='tips',bins=20,
    kde=True,
    color='blue',edgecolor='red',binwidth=0.5,multiple='layer',stat='probability',element='bars',fill=True,shrink=1,legend=False,linewidth=6,alpha=.1,palette='deep')
# Find mean
mean_value = df['tips'].mean()
# Show mean
print("Mean =", mean_value)

# Find median
mean_value = df['tips'].median()
# Show mean
print("Median =", mean_value)

# Find mode
mean_value = df['tips'].mode()
# Show mode
print("Mode =", mean_value)

ValueError: Could not interpret value `tips` for `x`. An entry with this name does not appear in `data`.

In [ ]:
# Import libraries
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

# Load dataset
df = pd.read_csv('tip.csv')

# Keep only two columns
df = df[['total_bill', 'tip']]

# INPUT (X) and OUTPUT (y)
X = df[['total_bill']]   # Input column
y = df['tip']            # Output column

# Split data into training and testing
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Create model
model = LinearRegression()

# Train model
model.fit(X_train, y_train)

# Predict test data
y_pred = model.predict(X_test)

# Show model score
print("Accuracy:", model.score(X_test, y_test))

# Show equation
print("Intercept:", model.intercept_)
print("Slope:", model.coef_[0])

# -----------------------------------
# CHECK NEW INPUT AND OUTPUT
# -----------------------------------

# New input value
new_bill = [[10]]

# Predict tip
predicted_tip = model.predict(new_bill)

print("Predicted Tip:", predicted_tip[0])

In [ ]:
# Import libraries
import pandas as pd
import joblib

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

# Load dataset
df = pd.read_csv('tip.csv')

# Keep only two columns
df = df[['total_bill', 'tip']]

# INPUT (X) and OUTPUT (y)
X = df[['total_bill']]
y = df['tip']

# Split data
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Create model
model = LinearRegression()

# Train model
model.fit(X_train, y_train)

# Save model
joblib.dump(model, 'tip_predictor.pkl')

print("Model Saved Successfully")

In [ ]:
import pandas as pd
data = pd.read_csv('tip.csv')

# Select only numerical columns
numeric_cols = data.select_dtypes(include=['number']).columns
for col in numeric_cols:
    Q1 = data[col].quantile(0.25)
    Q3 = data[col].quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    outliers = data[(data[col] < lower) | (data[col] > upper)]
    print(f"\nColumn: {col}")
    print(f"Number of Outliers: {len(outliers)}")
    print(outliers[[col]])
    import matplotlib.pyplot as plt

plt.boxplot(data['total_bill'])
plt.title("Boxplot of Total Bill")
plt.show()

less_count = (data['total_bill'] < median).sum()
greater_count = (data['total_bill'] > median).sum()

print("Median:", median)
print("Values less than median:", less_count)
print("Values greater than median:", greater_count)

In [46]:
data=pd.read_csv('synthetic_dataset.csv')
# Count missing values in the 'total_bill' column
data
missing_percentage = (data['Price'].isnull().sum() / len(data)) * 100
print("Missing Percentage:", missing_percentage, "%")
print("Missing values before CCA:", data['Price'].isnull().sum())
print("Shape before CCA:", data.shape)
# Complete Case Analysis
data_cca = data.dropna(subset=['Price'])
print("Missing values after CCA:", data_cca['Price'].isnull().sum())
print("Shape after CCA:", data_cca.shape)
rows_removed = len(data) - len(data_cca)
print("Rows removed:", rows_removed)
data_cca['Price'].isnull().sum()
data_cca

Missing Percentage: 3.988995873452544 %
Missing values before CCA: 174
Shape before CCA: (4362, 5)
Missing values after CCA: 0
Shape after CCA: (4188, 5)
Rows removed: 174

     Category   Price    Rating         Stock  Discount
0         NaN  5548.0  1.870322           NaN       0.0
1         NaN  3045.0  4.757798           NaN      38.0
2         NaN  4004.0       NaN      In Stock       0.0
3         NaN  4808.0  1.492085           NaN      33.0
4         NaN  1817.0       NaN  Out of Stock      23.0
...       ...     ...       ...           ...       ...
4354      NaN  1556.0  1.433035      In Stock       NaN
4357      NaN  4436.0  4.728335           NaN      49.0
4358        B  6236.0       NaN  Out of Stock       4.0
4359      NaN  3283.0       NaN  Out of Stock       9.0
4360        D  2999.0  4.425995           NaN      40.0

[4188 rows x 5 columns]

In [44]:
#Mean and Median of Total Bills Column
print(data['total_bill'].median())
print(data['total_bill'].mean())
#Mode of sex column
print(data['sex'].mode())
#Mean and Median of Tip Column
print(data['tip'].median())
print(data['tip'].mean())
#Mean and Median of size column
print(data['size'].median())
print(data['size'].mean())
less_count = (data['size'] < median)
greater_count = (data['size'] > median)

KeyError: 'total_bill'

     Category   Price    Rating         Stock  Discount
0         NaN  5548.0  1.870322           NaN       0.0
1         NaN  3045.0  4.757798           NaN      38.0
2         NaN  4004.0       NaN      In Stock       0.0
3         NaN  4808.0  1.492085           NaN      33.0
4         NaN  1817.0       NaN  Out of Stock      23.0
...       ...     ...       ...           ...       ...
4357      NaN  4436.0  4.728335           NaN      49.0
4358        B  6236.0       NaN  Out of Stock       4.0
4359      NaN  3283.0       NaN  Out of Stock       9.0
4360        D  2999.0  4.425995           NaN      40.0
4361      NaN     NaN  2.184471           NaN       0.0

[4362 rows x 5 columns]

In [40]:
# Complete Case Analysis
data_cca = data.dropna(subset=['Price'])

In [42]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Assuming:
# df_before = your dataframe before CCA
# df_after  = your dataframe after CCA

# --- 1. Summary statistics ---
print("Before CCA:\n", df_before['price'].describe())
print("\nAfter CCA:\n", df_after['price'].describe())

# --- 2. Side-by-side histograms ---
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

sns.histplot(df_before['price'], kde=True, ax=axes[0], color='steelblue')
axes[0].set_title('Price Distribution - Before CCA')

sns.histplot(df_after['price'], kde=True, ax=axes[1], color='darkorange')
axes[1].set_title('Price Distribution - After CCA')

plt.tight_layout()
plt.show()

# --- 3. Overlayed distribution plot ---
plt.figure(figsize=(8, 5))
sns.kdeplot(df_before['price'], label='Before CCA', fill=True, alpha=0.4)
sns.kdeplot(df_after['price'], label='After CCA', fill=True, alpha=0.4)
plt.title('Price Distribution Comparison')
plt.legend()
plt.show()

# --- 4. Boxplots to compare spread/outliers ---
plt.figure(figsize=(8, 5))
plt.boxplot([df_before['price'].dropna(), df_after['price'].dropna()],
            labels=['Before CCA', 'After CCA'])
plt.title('Price Boxplot Comparison')
plt.show()

NameError: name 'df_before' is not defined